[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build']

# Aponte para o diretório correto que contém o index.html e outros assets.
[start]
cmd = 'caddy file-server --browse --root dist/front-web/browser'
