[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build']

# Aponte para a pasta 'browser', que é o nosso novo outputPath.
[start]
cmd = 'caddy file-server --browse --root browser'
